services:
 prometheus:
  container_name: prometheus
  restart: unless-stopped
  image: prom/prometheus
  volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  depends_on:
    - cadvisor
    - node_exporter
 cadvisor:
   image: gcr.io/cadvisor/cadvisor:latest
   container_name: cadvisor
   volumes:
     - /:/rootfs:ro
     - /var/run:/var/run:rw
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro
   depends_on:
     - redis

 redis:
    image: redis:latest
    container_name: redis

 node_exporter:
  image: quay.io/prometheus/node-exporter:latest
  container_name: node_exporter
  command:
    - '--path.rootfs=/host'
  restart: unless-stopped
  volumes:
    - '/:/host:ro,rslave'

 grafana:
  image: grafana/grafana-enterprise
  container_name: grafana
  restart: unless-stopped
  ports:
    - '3000:3000'
  volumes:
    - grafana_storage:/var/lib/grafana

 mongo-team:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_team_data:/data/db
    
 mysql-driver:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_driver_data:/var/lib/mysql
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-gp:
  image: mysql:latest
  ports:
    - 3307:3306
  restart: unless-stopped
  volumes:
    - mysql_gp_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 driver-service:
  depends_on:
    - mysql-driver
  image: janpeterd/driver-service:latest
  ports:
    - 8081:8081
  links:
    - mysql-driver
  # HERE YOU HAVE TO USE 3306 INTERNAL PORT !!!!!
  # DOCKER NETEWORK (DOCKER DNS) uses internal ports
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-driver
   MYSQL_DB_PORT: 3306

 team-service:
  depends_on:
    - mongo-team
  image: janpeterd/team-service:latest
  ports:
    - 8080:8080
  links:
    - mongo-team
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-team
   DRIVER_SERVICE_BASEURL: driver-service:8081
 

 gp-service:
  depends_on:
    - driver-service
    - team-service
    - mysql-gp
  image: janpeterd/gp-service:latest
  ports:
    - 8082:8082
  links:
    - driver-service
    - team-service
  environment:
   DRIVER_SERVICE_BASEURL: driver-service:8081
   TEAM_SERVICE_BASEURL: team-service:8080
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-gp
   MYSQL_DB_PORT: 3306

 image-service:
  image: janpeterd/formula1-image-service:latest
  ports:
    - 8084:8084

 api-gateway:
   depends_on:
     - driver-service
     - team-service
     - gp-service
     - image-service
   image: janpeterd/formula1-api-gateway:latest
   ports:
     - 8083:8083
   links:
     - driver-service
     - team-service
     - gp-service
     - image-service
   environment:
     DRIVER_SERVICE_BASEURL: driver-service:8081
     TEAM_SERVICE_BASEURL: team-service:8080
     GP_SERVICE_BASEURL: gp-service:8082
     IMAGE_SERVICE_BASEURL: image-service:8084


volumes:
 mongodb_team_data:
 mysql_driver_data:
 mysql_gp_data:
 grafana_storage:

