apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formula1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: microservices.formula1.ms
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: formula1-frontend
            port:
              number: 80
  - host: api.microservices.formula1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8083
  - host: monitoring.microservices.formula1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
