apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-team-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Leave empty if the PV does not have a storage class
