apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gp
  template:
    metadata:
      labels:
        app: mysql-gp
    spec:
      containers:
      - name: mysql-gp
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-gp-secret
              key: password
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-gp-pvc
